FROM apache/spark:3.5.6-python3.11-jammy-fips-rfcurated

USER 0 
RUN apt update

RUN apt install -y build-essential

RUN cd /etc/apt

RUN cat /var/lib/dpkg/status

# continue -> next breakpoint
# next -> next line of dockerfile
# exec -> shell into container

# extension
# performance improvement, multi image import, reverse debugging, revoke, recording of logging
# immediately needed
# logging for import 
# get_df_dep.sh | xargs buildg import rfubu scratch , rfubu, 

# container -> writable layer on top of readonly